language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Dist::Zilla::App::Command::cover App::cpm
   - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
   - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -v -g $(dzil listdeps --author --missing)
script:
   - dzil smoke --release --author && dzil cover -test -report codecov


