language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
script:
    - perl Build.PL && ./Build build && cover -test
after_success:
    - cover -report codecov
